/* Builds VOCAB-REVIEW-QUEUE.md and cards-without-scope.csv from the course data
   and the 36-target plan. Reads only; publishes nothing; changes no card.

     node design/review/build-queue.js                                       */
const fs = require('fs'), path = require('path');
const ROOT = path.resolve(__dirname, '../..');
global.window = global;
['courses', 'month1', 'month2', 'month3', 'situations', 'dialect', 'flags'].forEach(f => require(path.join(ROOT, 'data', f + '.js')));
const D = window.DARIJA;

/* every object with an id anywhere in the content, and what it is */
const index = {};
function walk(x, where) {
  if (Array.isArray(x)) return x.forEach((y, i) => walk(y, where));
  if (!x || typeof x !== 'object') return;
  if (typeof x.id === 'string' && (x.en || x.phon || x.title || x.lines || x.turns))
    index[x.id] = index[x.id] || { where, en: x.en || x.title || '', phon: x.phon || (x.full && x.full.phon) || '', scope: x.scope || '', source: x.source || '' };
  Object.keys(x).forEach(k => walk(x[k], k === 'vocab' || k === 'extras' ? 'card' : k === 'sentences' ? 'sentence'
    : k === 'dialogues' || k === 'turns' ? 'dialogue' : k === 'lines' ? 'line' : where));
}
['month1', 'month2', 'month3'].forEach(m => walk(D[m], m));
D.situations.forEach(s => { index[s.id] = { where: 'situation', en: s.title, phon: '', scope: '', source: '' }; });

/* the CSV, parsed with quoted fields */
function parseCSV(t) {
  const rows = []; let row = [], f = '', q = false;
  for (let i = 0; i < t.length; i++) {
    const ch = t[i];
    if (q) { if (ch === '"' && t[i + 1] === '"') { f += '"'; i++; } else if (ch === '"') q = false; else f += ch; }
    else if (ch === '"') q = true; else if (ch === ',') { row.push(f); f = ''; }
    else if (ch === '\n') { row.push(f); rows.push(row); row = []; f = ''; } else if (ch !== '\r') f += ch;
  }
  if (f || row.length) { row.push(f); rows.push(row); }
  const head = rows.shift().map(h => h.replace(/^﻿/, ''));
  return rows.filter(r => r.length > 1).map(r => Object.fromEntries(head.map((h, i) => [h, r[i] || ''])));
}
const plan = parseCSV(fs.readFileSync(path.join(__dirname, 'vocabulary-expansion-36-targets.csv'), 'utf8'));

function check(token) {
  token = token.trim(); if (!token) return null;
  const range = token.split('..');
  const ids = range.length === 2 ? [range[0], range[1]] : [token];
  const found = ids.map(id => index[id]);
  return { token, ok: found.every(Boolean), what: found.map(x => x ? x.where : 'NOT FOUND').join(' … ') };
}

const FIRST = ['change', 'cash', 'price', 'takeaway', 'appointment', 'late', 'phone number', 'address', 'credit', 'deliver', 'key', 'twenty'];
let md = '# Vocabulary review queue\n\n' +
  'Prepared for Ahmed. **Nothing here is published.** These are communicative targets from the 10 October ' +
  'research plan (`vocabulary-expansion-36-targets.csv`, kept beside this file), not verified Tetouani words. ' +
  'Each needs Ahmed\'s exact Latin form, Arabic with checked harakat, scope, one approved example and a review ' +
  'date before it becomes a card. Generated by `build-queue.js` from the current course data; re-run it after any content change.\n\n' +
  '**Existing coverage** below checks that each referenced ID really exists in the course today. It is a lead for ' +
  'review, never permission to merge or rename anything.\n\n';
md += '## First batch: choose six to twelve with Ahmed\n\n| ID | Target | Existing coverage (checked) | Status |\n|---|---|---|---|\n';
const first = plan.filter(r => FIRST.some(k => r.communicative_target_english.toLowerCase().indexOf(k) >= 0)).slice(0, 12);
const row = r => {
  const refs = (r.existing_ids_or_situation_ids || '').split(';').map(check).filter(Boolean);
  const cov = refs.length ? refs.map(x => (x.ok ? '' : '⚠ ') + '`' + x.token + '` ' + x.what).join('<br>') : 'none listed';
  return '| ' + r.proposal_id + ' | ' + r.communicative_target_english + ' | ' + cov + ' | ' + (r.scope_or_review_status || 'pending Ahmed') + ' |\n';
};
first.forEach(r => md += row(r));
md += '\n## All 36 targets\n\n| ID | Context | Target | Coverage type | Existing coverage (checked) | Status |\n|---|---|---|---|---|---|\n';
plan.forEach(r => {
  const refs = (r.existing_ids_or_situation_ids || '').split(';').map(check).filter(Boolean);
  const cov = refs.length ? refs.map(x => (x.ok ? '' : '⚠ ') + '`' + x.token + '` ' + x.what).join('<br>') : '—';
  md += '| ' + r.proposal_id + ' | ' + r.context + ' | ' + r.communicative_target_english + ' | ' + r.coverage + ' | ' + cov + ' | ' + (r.scope_or_review_status || '') + ' |\n';
});

/* the inherited forms the brief names: do they exist where it says? */
const all = JSON.stringify(D);
md += '\n## Forms already in the course, named as candidates for a standalone card\n\n' +
  'Found in existing sentences or dialogues. Being in the repository is not a new confirmation: check the ' +
  'surrounding sentence, agreement and review status before extracting a card.\n\n| Form | Meaning given | Found |\n|---|---|---|\n';
[['s-SAK dya-LI', 'my bag'], ['sar-DEEN', 'sardine'], ['DER-hem', 'dirham'], ['m-SED-da', 'closed'], ['l-HA-nut', 'the shop'],
 ['n-SEL-hu', 'fix it'], ['s-skhu-NA', 'fever'], ['SHBE3T', 'I am full'], ['tla-TEEN', 'thirty']].forEach(([f, m]) => {
  const hits = Object.keys(index).filter(id => (index[id].phon || '').indexOf(f) >= 0);
  md += '| `' + f + '` | ' + m + ' | ' + (hits.length ? hits.map(h => '`' + h + '` (' + index[h].where + ')').join(', ')
    : (all.indexOf(f) >= 0 ? 'present in content (inside a longer line)' : '⚠ not found')) + ' |\n';
});

/* cards with no scope recorded: listed for review, not labelled */
const cards = [];
['month1', 'month2', 'month3'].forEach(m => {
  D[m].weeks.forEach(w => (w.vocab || []).forEach(c => cards.push([m, 'week ' + w.number, c])));
  (D[m].extras || []).forEach(c => cards.push([m, 'extra', c]));
});
const noScope = cards.filter(([, , c]) => !c.scope);
fs.writeFileSync(path.join(__dirname, 'cards-without-scope.csv'), 'id,month,where,english,latin,variety,marker,source\n' +
  noScope.map(([m, w, c]) => [c.id, m, w, c.en, c.phon, c.variety || '', c.marker ? 'yes' : '', c.source || '']
    .map(v => '"' + String(v).replace(/"/g, '""') + '"').join(',')).join('\n') + '\n');
md += '\n## Cards with no scope recorded\n\n' + noScope.length + ' of ' + cards.length + ' cards have no `scope` ' +
  '(mdini, tetouan or north). They are listed in `cards-without-scope.csv` for review. They have **not** been ' +
  'labelled: a missing scope is unknown, not Tetouani. ' + cards.filter(([, , c]) => c.source === 'draft').length +
  ' cards carry `source: draft`, which is likewise not verification.\n';
fs.writeFileSync(path.join(__dirname, 'VOCAB-REVIEW-QUEUE.md'), md);
console.log('targets', plan.length, '| first batch', first.length, '| no scope', noScope.length,
  '| broken references', plan.reduce((n, r) => n + (r.existing_ids_or_situation_ids || '').split(';').map(check).filter(x => x && !x.ok).length, 0));
